
@startuml Metadata

class Project {
  ID: String!
  Name: String!
  Title: String!
  ShortTitle: String!
  Keywords: [String]!
  Description: String!
  Year: Date!
  Public: Boolean!
  Species: [Species]!
  PublicationDOIs: [Publication]!
  Links: [Link]
  License: [License]!
  Contributor: [Contributor]
  GrantName: [FundingName]
  GrantNumber: [String]
  DateCreated: Date!
  DateModified: Date
  Protocol: DOI
  BossDBURIs: [String]!
  --
  ImageBanner: String!
  ImageTile: String!
  ImageHero: String
  --
  Collections: [Collection]
  Experiments: [Experiment]
  Channels: [Channel]
}

Project::PublicationDOIs *-- Publication
Project::Species *-- Species
Project::Links *-- Link
Project::Contributor *-- Contributor
Project::License *-- License
Project::GrantName *-- FundingName
Project::Collections *-- Collection
Project::Experiments *-- Experiment
Project::Channels *-- Channel
Project::Protocol *-- DOI

class Collection {
  ID: String!
  Name: String!
  BossDBURI: String
  Title: String
  Description: String!
  Public: Boolean!
  Creator: [User]!
  Contributors: [Contributor]!
  DateCreated: Date!
  DateModified: Date
  License: [License]!
  Organization: [String]
  GrantNumber: [String]
  Version: String
  --
  Species: [Species]
  --
  Experiments: [Experiment]
}

Collection::Creator *-- User
Collection::Contributors *-- Contributor
Collection::License *-- License
Collection::Species *-- Species
Collection::Experiments *-- Experiment

class Experiment {
  ID: String!
  Name: String!
  BCDCCollection: String
  BossDBURI: String!
  SampleType: String
  Description: String!
  Public: Boolean!
  Investigator: [User]!
  Contributors: [Contributor]!
  DateCreated: Date!
  DateModified: Date
  License: License!
  --
  SpeciesCommonName: Species!
  SpeciesTaxonomy: String
  Genotype: String
  SubjectID: String
  Age: String
  Sex: String
  Modality: String
  ImageLocation: BrainLocation
  Protocol: DOI
  Technique: ImageModalityGeneral
  AnatomicalStructure: [String]
  ParentSpecimen: [String]
  ParentSpecimenType: String
  SubspecimenType: String
  SubspecimenQuantity: Number
  --
  CoordinateFrame: CoordinateFrame!
  --
  Channels: [Channel]
  --
  Version: String
}

Experiment::Investigator *-- User
Experiment::Contributors *-- Contributor
Experiment::License *-- License
Experiment::ImageLocation *-- BrainLocation
Experiment::ImageLocation *-- Link
Experiment::CoordinateFrame *-- CoordinateFrame
Experiment::Channels *-- Channel

class Channel{
  ID: String!
  Name: String!
  BCDCCollection: String
  BossDBURI: String
  ArchiveURL: Link
  Description: String!
  Public: Boolean!
  Creator: [User]!
  Contributors: [Contributor]!
  DateCreated: Date!
  DateModified: Date
  License: License!
  Technique: ImagingModalityGeneral!
  ImageResolution: ImageResolution!
  VisualationColor: String
  ImageExtent: Number
  --
  VisualizationColor: String
  --
  Version: String
}

Channel::Creator *-- User
Channel::Contributors *-- Contributor
Channel::License *-- License
Channel::Technique *-- ImagingModalityGeneral
Channel::ImageResolution *-- ImageResolution
Channel::ChannelType *-- ChannelType
Channel::DataType *-- DataType
Channel::ArchiveURL *-- Link

class BrainLocation {
  Name: String!
  Location: DataLocation
}

BrainLocation::DataLocation *-- DataLocation

class DataLocation {
  URI: String
  Xs: [Number]
  Ys: [Number]
  Zs: [Number]
  Ts: [Number]
  Resolution: ImageResolution
}

class Publication {
  Name: [String]
  URI: [String]
  Authors: [String]
}

class Link {
  Name: [String]
  URI: [String]
}

class FundingName {
  Sponsor: [String]
  GrantName: [String]

}

class Contributor {
  Name: [String]
  Email: [String]
}

class License {
  License: String!
  URI: String!
}

class DOI {
  URI: String!
}

enum Species {
  CElegans
  FruitFly
  Mouse
  Zebrafish
  Zebrafinch
  Human
}

enum DataType {
  Imagery
  Segmentation
  Skeletons
  Connectome
}

enum ChannelType {
  Image
  Segmentation
  Annotation
}

enum ImagingModalityGeneral {
  SEM
  TEM
  XRay
  MRI
  LightMicroscopy
  None
}

enum ImagingModalitySpecific {
  ATUM_SEM
  SB_SEM
  SS_TEM
  S_TEM
  AT_TEM
  XRM
  XNH
  CLARITY
  MRI
  MRI_DTI
  None
}

class User {
  Name: String
  Email: String
}

class CoordinateFrame {
  Xs: [Number]
  Ys: [Number]
  Zs: [Number]
  --
  VoxelSize: ImageResolution
}

CoordinateFrame::ImageResolution *-- ImageResolution

class ImageResolution {
  VoxelSize: [Number]
  VoxelUnit: VoxelUnit
}
ImageResolution::VoxelUnit *-- VoxelUnit

enum VoxelUnit {
  nanometer
  micrometer
  millimeter
  centimeter
}

@endumlml
